# Generated by Django 5.2.14 on 2026-05-14 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('contract', 'Contract'), ('slip', 'Slip')], default='slip', max_length=20)),
                ('status', models.CharField(choices=[('reviewing', 'Đang xem xét'), ('in_progress', 'Đang thực hiện'), ('completed', 'Hoàn tất'), ('cancelled', 'Hủy bỏ')], default='reviewing', max_length=20)),
                ('content', models.TextField()),
                ('participants', models.JSONField(blank=True, default=list)),
                ('project_information', models.JSONField(blank=True, default=dict)),
                ('requesting_unit', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
