# Generated by Django 6.0.5 on 2026-05-16 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_requests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='customer',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Customers'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_requests', to=settings.AUTH_USER_MODEL, verbose_name='Khách hàng'),
        ),
        migrations.AddField(
            model_name='request',
            name='manager',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name__in': ['Managers', 'Technicians']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_requests', to=settings.AUTH_USER_MODEL, verbose_name='Người quản lý'),
        ),
    ]
