# Generated by Django 5.2.14 on 2026-05-10 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='participants',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('reviewing', 'Đang xem xét'), ('in_progress', 'Đang thực hiện'), ('completed', 'Hoàn tất'), ('cancelled', 'Hủy bỏ')], default='reviewing', max_length=20),
        ),
    ]
