# Generated by Django 5.2.14 on 2026-05-10 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_form', '0002_request_participants_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='project_information',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='request',
            name='requesting_unit',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
