# Generated by Django 6.0.5 on 2026-05-18 04:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_tests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='materialtest',
            name='reviewer',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Managers'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_tests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='materialtest',
            name='status',
            field=models.CharField(choices=[('in_progress', 'Đang thực hiện'), ('completed', 'Hoàn tất')], default='in_progress', max_length=20),
        ),
        migrations.AddField(
            model_name='materialtest',
            name='tester',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Technicians'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tests', to=settings.AUTH_USER_MODEL),
        ),
    ]
